[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ai_tremp_vote = "VoTe1xTNu9TrjAkRtigwACepUN94d2tfSyL23opuFGy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/codingfu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
